fixe(base-cluster): Add new env variable registry to loki-stack
4ALLPORTAL/helm-charts pull request #108
Opened 2023-04-17 12:51 UTC by tasches

Error in daemonset promtail. 
The image url is docker.io/<private registry>/grafana/promtail. It should either be docker.io/grafana/promtail or <private-registry>/grafana/promtail. 
This error occured because a default value was set in the subchart loki-stack.

2023-04-23 09:11 UTC, mstroecker requested changes

2023-04-23 09:11 UTC, mstroecker commented on charts/base-cluster/templates/monitoring/loki-stack.yaml
> +	registry: "{{ $.Values.global.imageRegistry }}"
```suggestion
        registry: "{{ $.Values.global.imageRegistry }}"
```

2023-04-28 13:39 UTC, tasches commented on charts/base-cluster/Chart.yaml
> +version: 35.0.10
```suggestion
version: 35.0.11
```

2023-04-28 13:42 UTC, mstroecker approved these changes

2023-04-28 13:50 UTC, merged