refactor(base-cluster): deleting everything with deadMansSwitch
4ALLPORTAL/helm-charts pull request #148
Opened 2023-06-05 13:30 UTC by CrocodileHunter8

Deleting everything with deadManSwitch
@tasches did i do everything right in regard of the version numbers + the change of the version number in the 4allportal helm chart?

For Ticket: CL-45:
https://jira.4allportal.net/browse/CL-45

2023-06-05 14:04 UTC, tasches requested changes

2023-06-05 14:04 UTC, tasches commented on charts/4allportal/Chart.yaml
> +version: 19.0.43
you haven't changed anything in the 4allportal chart so no version bump necessary

2023-06-05 14:04 UTC, tasches commented on charts/base-cluster/Chart.yaml
> +version: 37.0.7
you have removed a functionality of the base-cluster chart which is considered a breaking change.
The have to increase the major and not the patch version

2023-06-05 14:06 UTC, tasches commented
Error in values.schema. See pipeline. Fix necessary

2023-06-05 14:17 UTC, tasches requested changes

2023-06-05 14:17 UTC, tasches commented on charts/base-cluster/values.schema.json
> +        },
still errors in the schema.

2023-06-13 10:46 UTC, tasches requested changes
No documentation was added. Because this is a major release and there are breaking changes due to the removal of the deadmanswitch. You need a documentation. You can try it yourself. Use an old values file with deadmanswitch enbaled and try the update. It will fail. See values.schema

2023-06-14 08:01 UTC, tasches requested changes

2023-06-14 11:57 UTC, CrocodileHunter8 commented on charts/base-cluster/README.md
> +This release removes everything related to the deadMansSwitch function
i add it

2023-06-21 10:12 UTC, closed without merging

2023-06-21 10:13 UTC, tasches commented
rejected