feat(4allportal): add samba to 4allportal chart
4ALLPORTAL/helm-charts pull request #275
Opened 2024-11-27 10:02 UTC by C-schwarz-4ap

2024-11-27 11:01 UTC, mstroecker commented on charts/4allportal/templates/samba/deployment.yaml
> +                - timeout 1 ls -d /dav/data/samba/data
I am confused, isn't it /mnt/assets and where is data?

2024-11-27 12:34 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/secret.yaml
> +            "password": "CjXYjwF7kqLaf2NbAqTSdAUqS"
Auto generate or set via value, unconfigurable default via HelmChart is a massive security risk

2024-11-27 12:35 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/configmap.yaml
> +{{- if $.Values.samba.enabled }}
Why $.Values instead of .Values? Curious

2024-11-27 12:35 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/configmap.yaml
> +            "assets"
Data share missing

2024-11-27 12:35 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/configmap.yaml
> +        "assets": {
Data share missing

2024-11-27 12:36 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/deployment.yaml
> +                - timeout 1 ls -d /mnt/assets
Data mount in liveness

2024-11-27 12:37 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/deployment.yaml
> +        {{- include "4allportal.fourallportal.persistence.assets.mount" $ | nindent 10 }}
Data mount

2024-11-27 12:38 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/deployment.yaml
> +        {{- include "4allportal.fourallportal.persistence.assets.mount" $ | nindent 10 }}
Also missing "4allportal.fourallportal.persistence.assets.mount" as template

2024-11-27 12:38 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/secret.yaml
> +            "password": "CjXYjwF7kqLaf2NbAqTSdAUqS"
Auto generation would also mean regenerating admin password per restart

2024-11-27 16:01 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/deployment.yaml
> +        {{- include "4allportal.fourallportal.persistence.config.mount" $ | nindent 10 }}
Still can't find template for this and assets.mount, or is that an existing value?

2024-11-27 16:02 UTC, jpkraemer-mg commented on charts/4allportal/templates/samba/deployment.yaml
> +        {{- include "4allportal.fourallportal.persistence.config.mount" $ | nindent 10 }}
nevermind, exists already

2024-11-27 20:39 UTC, mstroecker requested changes

2024-11-27 20:39 UTC, mstroecker commented on charts/4allportal/templates/samba/configmap.yaml
> +       "config": {
It is probably wise to also call it data for consistency.

2024-11-27 20:39 UTC, mstroecker commented on charts/4allportal/templates/samba/deployment.yaml
> +              value: assets
Not super important, but identifying the config for assets and config(data) with the name assets could be a bit confusing later on.

2024-11-28 12:24 UTC, mstroecker approved these changes
LGTM

2024-11-28 12:35 UTC, merged